//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoFamiliarPoli.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class grupo_familiar
    {
        [Key, Column(Order = 0)]
        public int id_familiar { get; set; }
        [Key, Column(Order = 1)]
        public long id_paciente { get; set; }
        public string nom_familiar { get; set; }
        public Nullable<int> num_telefono { get; set; }
        public string num_id { get; set; }
        public string email { get; set; }
        public System.DateTime fecha_ultima_visita { get; set; }
    }
}
